version: "3"

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: jwt-auth-demo_postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: