version: "3"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: jwt-auth-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: jwt-auth-demo_postgres
    ports:
      - 54320:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - db-data:/var/lib/postgresql/data
# Add volumes definition to create volume mysql-data referenced above
volumes:
  db-data: